export enum CurrentWeatherModelKeysToRequestKeys {
  'temperature' = 'temperature_2m',
  'humidity' = 'relative_humidity_2m',
  'apparentTemperature' = 'apparent_temperature',
  'precipitation' = 'precipitation',
  'rain' = 'rain',
  'showers' = 'showers',
  'snowfall' = 'snowfall',
  'cloudCover' = 'cloud_cover',
  'pressure' = 'pressure_msl',
  'surfacePressure' = 'surface_pressure',
  'windSpeed' = 'wind_speed_10m',
  'windDirection' = 'wind_direction_10m',
  'windGusts' = 'wind_gusts_10m',
  'time' = 'time',
}

export enum CurrentWeatherModelKeys {
  'temperature' = 'temperature',
  'humidity' = 'humidity',
  'apparentTemperature' = 'apparentTemperature',
  'precipitation' = 'precipitation',
  'rain' = 'rain',
  'showers' = 'showers',
  'snowfall' = 'snowfall',
  'cloudCover' = 'cloudCover',
  'pressure' = 'pressure',
  'surfacePressure' = 'surfacePressure',
  'windSpeed' = 'windSpeed',
  'windDirection' = 'windDirection',
  'windGusts' = 'windGusts',
  'time' = 'time',
}

export enum CurrentWeatherResponseKeysToModelKeys {
  'time' = 'time',
  'temperature_2m' = 'temperature',
  'relative_humidity_2m' = 'humidity',
  'apparent_temperature' = 'apparentTemperature',
  'precipitation' = 'precipitation',
  'rain' = 'rain',
  'showers' = 'showers',
  'snowfall' = 'snowfall',
  'cloud_cover' = 'cloudCover',
  'pressure_msl' = 'pressure',
  'weather_code' = 'weatherCode',
  'surface_pressure' = 'surfacePressure',
  'wind_speed_10m' = 'windSpeed',
  'wind_direction_10m' = 'windDirection',
  'wind_gusts_10m' = 'windGusts',
  'is_day' = 'isDay',
}
