import { DirectionUnit } from '../response/direction.unit';
import { HeightUnit } from '../response/height.unit';
import { PercentageUnit } from '../response/percentage.unit';
import { PressureUnit } from '../response/pressure.unit';
import { SpeedUnit } from '../response/speed.unit';
import { TemperatureUnit } from '../response/temperature.unit';
import { RadiationResponseUnit } from './radiation.param';

export type HourlyRequest = {
  temperature_2m: TemperatureUnit;
  relative_humidity_2m: PercentageUnit;
  dew_point_2m: TemperatureUnit;
  apparent_temperature: TemperatureUnit;
  pressure_msl: PressureUnit;
  surface_pressure: PressureUnit;
  cloud_cover: PercentageUnit;
  cloud_cover_low: PercentageUnit;
  cloud_cover_mid: PercentageUnit;
  cloud_cover_high: PercentageUnit;
  wind_speed_10m: SpeedUnit;
  wind_speed_80m: SpeedUnit;
  wind_speed_120m: SpeedUnit;
  wind_speed_180m: SpeedUnit;
  wind_direction_10m: DirectionUnit;
  wind_direction_80m: DirectionUnit;
  wind_direction_120m: DirectionUnit;
  wind_direction_180m: DirectionUnit;
  wind_gusts_10m: SpeedUnit;
  shortwave_radiation: RadiationResponseUnit;
  direct_radiation: RadiationResponseUnit;
  direct_normal_irradiance: RadiationResponseUnit;
  diffuse_radiation: RadiationResponseUnit;
  global_tilted_irradiance: RadiationResponseUnit;
  precipitation: HeightUnit;
  snowfall: HeightUnit;
  rain: HeightUnit;
  showers: HeightUnit;
};
